using System;
using System.Collections.Generic;

namespace KICSAPI.Models
{
    public partial class Blogpost
    {
        public Blogpost()
        {
            Advertisement = new HashSet<Advertisement>();
            Blogpostcinemas = new HashSet<Blogpostcinemas>();
            Blogpostcomment = new HashSet<Blogpostcomment>();
            Blogpostmembertypes = new HashSet<Blogpostmembertypes>();
        }

        public Guid BlogPostId { get; set; }
        public DateTime CreateDateTime { get; set; }
        public DateTime ValidStartDateTime { get; set; }
        public DateTime ValidFinishDateTime { get; set; }
        public string Subject { get; set; }
        public string Text { get; set; }
        public bool IsSticky { get; set; }
        public bool? IsPublic { get; set; }
        public string Url { get; set; }
        public Guid? CompanyId { get; set; }
        public short BlogPostSectionId { get; set; }
        public Guid? MovieDetailId { get; set; }
        public Guid? PromotionId { get; set; }
        public Guid? CompetitionId { get; set; }
        public Guid? OfferId { get; set; }
        public Guid? PageId { get; set; }
        public Guid? ShopId { get; set; }
        public Guid AuthorUserId { get; set; }
        public bool IsAutoGenerated { get; set; }
        public short? CountryId { get; set; }
        public short LanguageId { get; set; }
        public int? AutoPostTypeId { get; set; }

        public AspnetUsers AuthorUser { get; set; }
        public Autoposttype AutoPostType { get; set; }
        public Blogpostsection BlogPostSection { get; set; }
        public Company Company { get; set; }
        public Competition Competition { get; set; }
        public Country Country { get; set; }
        public Language Language { get; set; }
        public Moviedetail MovieDetail { get; set; }
        public Offer Offer { get; set; }
        public Page Page { get; set; }
        public Promotion Promotion { get; set; }
        public Shop Shop { get; set; }
        public ICollection<Advertisement> Advertisement { get; set; }
        public ICollection<Blogpostcinemas> Blogpostcinemas { get; set; }
        public ICollection<Blogpostcomment> Blogpostcomment { get; set; }
        public ICollection<Blogpostmembertypes> Blogpostmembertypes { get; set; }
    }
}
